# Generated by Django 4.2.11 on 2024-03-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_recipetag_tag_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='category',
            new_name='tag',
        ),
    ]
